[package]
name = "bastion-config"
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow = "1.0.100"
directories = "6.0.0"
hex = "0.4.3"
ipnet = "2.11.0"
rand = "0.9.2"

[lints]
workspace = true
