[package]
name = "bastion-config"
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
directories = "6.0.0"
hex = "0.4.3"
ipnet.workspace = true
rand.workspace = true

[lints]
workspace = true
