[package]
name = "bastion-core"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.225", features = ["derive"] }
serde_json = "1.0.145"
uuid = { version = "1.18.1", features = ["serde", "v4"] }

[dev-dependencies]
assert-json-diff = "2.0.2"
